### ISSUE TITLE
Aigaion publication view --> keep text inside window

### ISSUE THREAD

**Issue by JGMonroy** [jlblancoc/aigaion2-mapir-arm#7]
A problem I've detected is that when we include the Rankings and Image URL for a given publication, since the resulting "userfields" is too long, some parts of the web-page are not properly displayed (this is on the "show publication" page where categorization is to be done).

A possible solution would be to limit the extension of the "userfields" displayed text.

What do you think?

**Comment by jlblancoc** [comment]
That one was easy! ;-) 

Done in the commit above.
